project:
  type: website
website:
  twitter-card: true
  # margin-header: suscribe.html
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-444BCYE4CQ"
    anonymize-ip: true
  title: "MRSE-H"
  favicon: iconoxd.png
  navbar:
    left:
      - fotos.qmd
      - noticias.qmd
      - Datos de monitoreo.qmd
    links:
      - icon: github
        href: https://github.com/Bryan1qr/MRSE-web-dev/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual

