project:
  type: website

website:
  margin-header: suscribe.html
  title: "Pruebas-mrse"
  navbar:
    right:
      - about.qmd
      - Datos de monitoreo.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

